@startsalt
{^"MHV Allergy box"
  Allergy: | "name of allergy (RxNorm)   "
  Date: | ^date^
  Severity: | ^Severe, Moderate, Mild^
  Diagnosed: | ^Yes, No^
  Reaction: | "reaction                                   "
  Comments: | "comments                                   "

  [  Save   ] | [  Save & Add Another  ] | [  Reset  ] | [  Cancel  ]
}
@endsalt