@startsalt
{^"My Medication box"
  Medication Name| "medication name (RxNorm)   "
  Reason| "reason for taking"
  Strength| "strength per dosage"
  Quantity per dose| ^0.5, 1, 2, 3, 4, 5, 6^
  Frequency of a dose| ^once a day, twice a day, three a day, four a day, once a week, ... , as needed^
  Method of a dose| ^Oral, rectal, transdermal, topical, intramucscuolar, intravenous^
  [] Side affects of the drug
  Start Date| ^date^
  Stop Date| ^date^
  [] Currently Taking
  RX Number| "prescription Number "
  Provider | "who prescribed"
  Pharmacy| "pharmacy"
  Phone of Pharmacy| "pharmacy phone"
  Notes| "comments"

  [  OK   ] | [Cancel]  
}
@endsalt